version: "3.9"

services:
  cdn:
    image: webdevops/php-nginx:8.2-alpine
    container_name: website
    restart: unless-stopped
    networks:
      - reverse_proxy
    volumes:
      - ./html:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: index.html
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    labels:
      traefik.enable: true
      traefik.http.routers.website.rule: Host(`valentincolin.com`)
      traefik.http.routers.website.entrypoints: websecure
      traefik.http.services.website.loadbalancer.server.port: 80
      traefik.http.routers.website.middlewares: gzip@file

networks:
  reverse_proxy:
    external: true
