version: "3.9"

services:
  website:
    image: valentincolin/website
    container_name: website
    restart: unless-stopped
    environment:
      PRODUCTION: "True"
    # build une image depuis un <docker-compose build website> au lieu de <docker build . -t valentincolin/website>
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - website

networks:
  website:
