version: "3.9"

services:
  website:
    image: valentincolin/website
    container_name: valentincolin_website
    restart: unless-stopped
    environment:
      PRODUCTION: "True"
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - reverse_proxy
    labels:
      caddy: valentincolin.com
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  reverse_proxy:
    external: true
